DEPS = \
       Makefile \
       ../base/common.mk \
       ../base/*.h \
       Electron.h \
       Particle.h \
       Photon.h \

OBJS = \
       Electron.o \
       Particle.o \
       Photon.o \

LIBS = \
       ../base/*.o \

#PROG = \
#       main.exe \

WRAPPER = \
       NanoPhys

include ../base/common.mk
