DEPS = \
       Makefile \
       common.mk \
       Arrow.h \
       Box.h \
       Color.h \
       Config.h \
       Entity.h \
       Misc.h \
       Sys.h \
       World.h \

OBJS = Arrow.o \
       Box.o \
       Color.o \
       Config.o \
       Entity.o \
       Misc.o \
       Sys_glut.o \
       World.o \

WRAPPER = \
       NanoBase

include common.mk
